### ISSUE TITLE
List: nested broken and with long content

### ISSUE THREAD

**Issue by atinux** [nuxt-themes/typography#17]
Markdown:

```md
- first item
- second item
  - nested item
- Another item
- **I often do this thing where list items have headings.**

  For some reason I think this looks cool which is unfortunate because it's pretty annoying to get the styles right.

  I often have two or three paragraphs in these list items, too, so the hard part is getting the spacing between the paragraphs, list item heading, and separate list items to all make sense. Pretty tough honestly, you could make a strong argument that you just shouldn't write this way.
- Last item
```

See result on https://typography.nuxt.space/example

To reproduce, run `npm run dev` and go to http://localhost:3000/example

See the same HTML applied with Tailwind prose: https://play.tailwindcss.com/QltRgFhkwd

![CleanShot 2022-11-28 at 14.17.19@2x.png](https://volta.s3.fr-par.scw.cloud/Clean_Shot_2022_11_28_at_14_17_19_2x_86187c2160.png)

**Comment by Tahul** [comment]
@bdrtsky ; have you had time to look at this?
