### ISSUE TITLE
When use `@nuxt-themes/typography`, `.vue` file `style` section was not works

### ISSUE THREAD

**Issue by aliuq** [nuxt-themes/typography#29]
[Link](https://stackblitz.com/edit/nuxt-theme-typography-jnomjq?file=app.vue,package.json,README.md)

![image](https://user-images.githubusercontent.com/11707934/216012523-5b568b90-b58c-471d-af4f-04eee9892c28.png)

**Comment by aliuq** [comment]
I found that this problem is caused by `pinceau`, I tested the last few versions, `v0.13.0` is correct, from `v0.13.1` onwards the problem appears

**Comment by Tahul** [comment]
Hello :)

I tried `^0.13.9` in your reproduction and it fixes the bug.

Thank you for reporting it, feel free to re-open if you encounter this issue again.
